### ISSUE TITLE
[Docker] Cannot find module 'dotenv'

### ISSUE THREAD

**Issue by senwang86** [codepod-io/codepod#536]
- `git pull` latest commit on SSDNode cloud server
- `docker-compose up -d --force-recreate`
- `web-yjs`,`web-api`,`spawner-docker` complains about `Error: Cannot find module 'dotenv'`
- Tried `pnpm add dotenv`, then `docker-compose up -d --force-recreate`, the complain persists.

===========================
[INFO] 19:20:42 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.1, typescript ver. 4.8.4)
Error: Cannot find module 'dotenv'
Require stack:
- /codepod/apps/web-yjs/src/run.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/codepod/apps/web-yjs/src/run.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._compile (/codepod/node_modules/.pnpm/source-map-support@0.5.21/node_modules/source-map-support/source-map-support.js:568:25)
    at Module.m._compile (/tmp/ts-node-dev-hook-45905237892175865.js:69:33)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-45905237892175865.js:114:20)
[ERROR] 19:21:13 Error: Cannot find module 'dotenv'
Require stack:
- /codepod/apps/web-yjs/src/run.ts

**Comment by lihebi** [comment]
I don't have this issue.

But those `require(dotenv)`s aren't required, because the ENV variables are directly set as ENV variable in docker `compose.yaml`, not loaded from an `.env` file.

**Comment by lihebi** [comment]
Should be fixed by #537. Please re-open if #537 doesn't fix this issue.

**Comment by senwang86** [comment]
#537 fixed the issue! Thanks!
